source "https://rubygems.org"

gem 'faker'
gem 'date'
gem 'cucumber'
gem 'json-schema-rspec'
gem 'rspec'
gem 'httparty'
gem 'pry'
gem 'capybara'
gem 'report_builder'
gem 'selenium-webdriver'
gem 'chromedriver-helper'
gem 'factory_bot'